Cypress.on('uncaught:exception', (err, runnable) => {
    return false;
});
import general_pom from "../../POM/general_pom";
import prodaja_pom from "../../POM/prodaja_pom";
describe("Positive cases Продажа", () => {
    beforeEach("Login", () => {
        cy.viewport(1700, 700)
        cy.login("medion_admin", "admin_medion123")
        general_pom.sidebar_icons.module_button().click()
        general_pom.selectors.select_item("Касса")
        general_pom.sidebar_icons.sellment_page_icon().click()
    })
   
    it("Create new Продажа", () => {
        cy.wait(2000)
        general_pom.table_buttons.add_button().click()
        cy.wait(2000)
        cy.get('._mainCardSide_14nop_9').scrollTo('top', {ensureScrollable: false})
        general_pom.table_buttons.add_form_submit_button().click()
        cy.wait(5000)
        cy.pastle(prodaja_pom.elements.product_code_field(), '3607341186393')
        cy.wait(2000)
        prodaja_pom.elements.payment_button().click()
        cy.wait(2000)
        prodaja_pom.elements.inner_add_button().click()
        cy.wait(5000)
        prodaja_pom.elements.inner_save_button().click()
        cy.wait(5000)
        general_pom.table_buttons.add_form_submit_button().click()
        cy.wait(5000)
    })
    it("Create new Продажа", () => {
        cy.wait(2000)
        general_pom.table_buttons.add_button().click()
        cy.wait(2000)
        cy.get('._mainCardSide_14nop_9').scrollTo('top', {ensureScrollable: false})
        general_pom.table_buttons.add_form_submit_button().click()
        cy.wait(5000)
        prodaja_pom.elements.Sertificate_button().click()
        cy.wait(2000)
        cy.pastle(prodaja_pom.elements.product_code_field(), 'aa-100829')
        cy.wait(2000)
        prodaja_pom.elements.payment_button().click()
        cy.wait(2000)
        prodaja_pom.elements.inner_add_button().click()
        cy.wait(5000)
        prodaja_pom.elements.inner_save_button().click()
        cy.wait(5000)
        general_pom.table_buttons.add_form_submit_button().click()
        cy.wait(5000)
    })
    it("Edit Продажа", () => {
        cy.wait(2000)
        general_pom.table_buttons.edit_button().click()
        cy.wait(1000)
        cy.get('.CTableBody').scrollTo('top', {ensureScrollable: false})
        prodaja_pom.elements.client_list_button().click({force: true})
        cy.wait(1000)
        prodaja_pom.elements.first_client_on_list().click()
        cy.wait(1000)
        general_pom.table_buttons.edit_save_button().click()
    })
    it("Open Продажа", () => {
        cy.wait(2000)
        general_pom.table_buttons.table_first_item().click()
        cy.wait(2000)
        prodaja_pom.elements.opened_item_header().should('have.text', '  Штрихкод:')
    })
    it("Delete Продажа", () => {
        cy.wait(2000)
        general_pom.table_buttons.table_first_item_delete_button().click({force: true})
    })
    it.only("Filter Продажа", () => {
        cy.wait(2000)
        prodaja_pom.elements.filter_by_filial_input().click()
        cy.wait(2000)
        
        general_pom.selectors.select_item('kontinent-1')
        cy.esc()
        cy.get(':nth-child(1) > ._autocomplete_sp167_1 > ._autocompleteButton_sp167_1').click()
        general_pom.selectors.select_item("Kontinent")
        cy.esc()
        cy.get(':nth-child(3) > ._autocomplete_sp167_1 > ._autocompleteButton_sp167_1').click()
        cy.get('.MuiList-root > .MuiFormControl-root > .MuiInputBase-root').find("input").first().type('Ko-0000002')
        // prodaja_pom.elements.filter_by_smena_input().type('Ko-0000002')
        // general_pom.selectors.select_item('Ko-0000002')
        // cy.esc()
        // prodaja_pom.elements.first_item_smena().contains('Ko-0000002')
    })
   
})